ALTER TABLE cargo
  ADD COLUMN IF NOT EXISTS way_points JSONB NULL,
  ADD COLUMN IF NOT EXISTS packaging_amount INTEGER NULL,
  ADD COLUMN IF NOT EXISTS is_two_drivers_required BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS unloading_types TEXT[] NULL;

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS payment_note VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS payment_terms_note TEXT NULL;
