-- Best-effort rollback (data may not round-trip perfectly).

ALTER TABLE trips DROP CONSTRAINT IF EXISTS trips_pending_confirm_check;
ALTER TABLE trips ADD CONSTRAINT trips_pending_confirm_check CHECK (
  pending_confirm_to IS NULL OR pending_confirm_to IN ('ASSIGNED', 'LOADING', 'EN_ROUTE', 'UNLOADING', 'COMPLETED')
);

ALTER TABLE trips DROP CONSTRAINT IF EXISTS trips_status_check;
UPDATE trips SET status = CASE status
  WHEN 'IN_PROGRESS' THEN 'PENDING_DRIVER'
  WHEN 'IN_TRANSIT' THEN 'EN_ROUTE'
  WHEN 'DELIVERED' THEN 'UNLOADING'
  ELSE status
END
WHERE status IN ('IN_PROGRESS', 'IN_TRANSIT', 'DELIVERED');
ALTER TABLE trips ADD CONSTRAINT trips_status_check CHECK (status IN (
  'PENDING_DRIVER', 'ASSIGNED', 'LOADING', 'EN_ROUTE', 'UNLOADING', 'COMPLETED', 'CANCELLED'
));

ALTER TABLE cargo DROP CONSTRAINT IF EXISTS cargo_status_check;
ALTER TABLE cargo ADD CONSTRAINT cargo_status_check CHECK (status IN (
  'CREATED', 'PENDING_MODERATION', 'REJECTED', 'SEARCHING_ALL', 'SEARCHING_COMPANY', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
));
